export const GLOBAL_SEARCH_ENABLED = 'GLOBAL_SEARCH_ENABLED';
export const GLOBAL_SEARCH_DISABLED = 'GLOBAL_SEARCH_DISABLED';
export const GLOBAL_SEARCH_TEXT_CHANGED = 'GLOBAL_SEARCH_TEXT_CHANGED';
export const SCOPED_NOTIFICATION_SHOW = 'SCOPED_NOTIFICATION_SHOW';
export const SCOPED_NOTIFICATION_CLOSE = 'SCOPED_NOTIFICATION_CLOSE';
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

